-- Crear tabla de equipos
CREATE TABLE equipos (
    idEquipo INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    img VARCHAR(50)
);

-- Crear tabla de jugadores
CREATE TABLE jugador (
    idJugador INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    nacionalidad VARCHAR(50),
    posicion VARCHAR(50),
    idEquipo INT,
    img VARCHAR(50),
    FOREIGN KEY (idEquipo) REFERENCES equipos(idEquipo)
);

-- Crear tabla de goles
CREATE TABLE goles (
    idGol INT PRIMARY KEY AUTO_INCREMENT,
    gol BOOLEAN NOT NULL,
    idJugador INT,
    lugarTiro INT,
    FOREIGN KEY (idJugador) REFERENCES jugador(idJugador)
);

-- Crear tabla de partidos
CREATE TABLE partidos (
    idPartido INT PRIMARY KEY AUTO_INCREMENT,
    idEquipo INT,
    idEquipoContrario INT,
    fecha DATE,
    torneo VARCHAR(50),
    sede VARCHAR(50),
    arranque BOOLEAN,
    marcadorF INT,
    marcadorC INT,
    minuto INT,
    ronda VARCHAR(50),
    FOREIGN KEY (idEquipo) REFERENCES equipos(idEquipo),
    FOREIGN KEY (idEquipoContrario) REFERENCES equipos(idEquipo)
);

-- insersion de equipos
INSERT INTO equipos (nombre,img) VALUES
('TIGRES','TIGRES.png'),
('MONTERREY','MONTERREY.png'),
('AMERICA','AMERICA.png'),
('SAN LUIS','SAN LUIS.png'),
('CRUZ AZUL','CRUZ AZUL.png'),
('PUMAS','PUMAS.png'),
('TIJUANA','TIJUANA.png'),
('ATLAS','ATLAS.png'),
('GUADALAJARA','GUADALAJARA.png'),
('NECAXA','NECAXA.png'), 
('LEON','LEON.png'),
('PUEBLA','PUEBLA.png'),
('JUAREZ','JUAREZ.png'),
('PACHUCA','PACHUCA.png'),
('QUERETARO','QUERETARO.png'),
('SANTOS','SANTOS.png');

-- insersion de jugadores
INSERT INTO jugadores (nombre, nacionalidad, posicion, idEquipo,img) VALUES
('André-Pierre Gignac', 'Francesa', 'Delantero', 1,'André-Pierre Gignac.png'),
('Sergio Canales', 'Españala', 'Centrocampista', 2,'Sergio Canales.png'),
('Henry Martin', 'Mexicana', 'Delantero', 3,'Henry Martin.png'),
('Franck Boli', 'Marfileña', 'Delantero', 4,'Franck Boli.png'),
('Carlos Rotondi', 'Argentina', 'Delantero', 5,'Carlos Rotondi.png'),
('Cesar Huerta', 'Mexicana', 'Delantero-extremo izquierdo', 6,'Cesar Huerta.png'),
('Christian Rivera', 'Colombiano', 'Mediocampista', 7,'Christian Rivera.png'),
('Aldo Rocha', 'Mexicana', 'Mediocampista defensivo', 8,'Aldo Rocha.png'),
('Roberto Alvarado', 'Mexicana', 'Mediocampista', 9,'Roberto Alvarado.png'),
('José Paradela', 'Argentina', 'Mediocampista', 10,'José Paradela.png'),
('Jhonder Cádiz', 'Venezolana', 'Delantero', 11,'Jhonder Cádiz.png'),
('Lucas Cavallini', 'Canadiense', 'Delantero', 12,'Lucas Cavallini.png'),
('Avilés Hurtado', 'Colombiana', 'Mediapunta o extremo', 13,'Avilés Hurtado.png'),
('Borja Bastón', 'Española', 'Delantero	', 14,'Borja Bastón.png'),
('Pablo Barrera', 'Mexicana', 'Volante o extremo por banda', 15,'Pablo Barrera.png'),
('Harold Preciado', 'Colombiana', 'Delantero central', 16,'Harold Preciado.png');

-- insersion de goles
INSERT INTO goles (gol, idJugador, lugarTiro) VALUES
(FALSE, 1, 6),(TRUE, 1, 6),(FALSE, 1, 4),(TRUE, 1, 4),(TRUE, 1, 4),(TRUE, 1, 5),
(TRUE, 1, 3),(TRUE, 1, 4),(TRUE, 1, 1),(TRUE, 1, 6),(TRUE, 1, 4),(TRUE, 1, 1),
(TRUE, 1, 1),(TRUE, 1, 4),(TRUE, 1, 1),(TRUE, 1, 4),(FALSE, 1, 10),(TRUE, 1, 1),
(FALSE, 1, 11),(TRUE, 1, 4),(TRUE, 1, 5),(TRUE, 1, 6),(TRUE, 1, 4),(TRUE, 1, 6),
(TRUE, 1, 4),(TRUE, 1, 4),(TRUE, 1, 6),(TRUE, 1, 2),(FALSE, 1, 6),(TRUE, 1, 6),
(TRUE, 1, 6),(FALSE, 1, 10),
-- goles Sergio Canales
(TRUE, 2, 6),(FALSE, 2, 4),  
(TRUE, 2, 2),(TRUE, 2, 6),(TRUE, 2, 4),  
(FALSE, 2, 6),(TRUE, 2, 4),(TRUE, 2, 6),  
(FALSE, 2, 8),(TRUE, 2, 6),(TRUE, 2, 4),  
(TRUE, 2, 4),(TRUE, 2, 6),(TRUE, 2, 4),  
-- Henry Martin 
(TRUE, 3, 1),(TRUE, 3, 4),(TRUE, 3, 6),  
(TRUE, 3, 6),(TRUE, 3, 6),(TRUE, 3, 4),  
(TRUE, 3, 4),(TRUE, 3, 3),(TRUE, 3, 3),  
(FALSE, 3, 5),  
-- Franck Boli	marfileña
(TRUE, 4, 4),(TRUE, 4, 5),(FALSE, 4, 6),  
(TRUE, 4, 6),(TRUE, 4, 4),(TRUE, 4, 5),  
(FALSE, 4, 9),(TRUE, 4, 3),(TRUE, 4, 4),  
(FALSE, 4, 4),  
-- Carlos Rotondi
(TRUE, 5, 4),(TRUE, 5, 4),(TRUE, 5, 4),  
-- Cesar Huerta
(FALSE, 6, 6),(TRUE, 6, 5),(FALSE, 6, 4),  
(TRUE, 6, 6),(TRUE, 6, 4),(TRUE, 6, 4),  
(TRUE, 6, 4), 
-- Christian Rivera
(TRUE, 7, 6),(TRUE, 7, 6),(TRUE, 7, 6),  
(TRUE, 7, 6),(TRUE, 7, 6),(TRUE, 7, 4),  
(TRUE, 7, 4),(TRUE, 7, 6), 
-- Aldo Rocha
(TRUE, 8, 4),(TRUE, 8, 4),(FALSE, 8, 10),  
(TRUE, 8, 5),(FALSE, 8, 6),(TRUE, 8, 6),  
(TRUE, 8, 6),(TRUE, 8, 4),(TRUE, 8, 6), 
(TRUE, 8, 4), 
-- Roberto Alvarado
(TRUE, 9, 1),(TRUE, 9, 4),(TRUE, 9, 4),  
(TRUE, 9, 4),(TRUE, 9, 6),(TRUE, 9, 4),  
(TRUE, 9, 6), 
-- José Paradela
(TRUE, 10, 6),(TRUE, 10, 4),(TRUE, 10, 6),  
(TRUE, 10, 6),(TRUE, 10, 6), 
-- Jhonder Cádiz
(TRUE, 11, 4),(FALSE, 11, 10),(TRUE, 11, 5),  
(TRUE, 11, 4),(TRUE, 11, 6),(TRUE, 11, 5),  
(TRUE, 11, 5), 
-- Lucas Cavallini
(TRUE, 12, 6),(TRUE, 12, 6),(TRUE, 12, 4), 
(TRUE, 12, 2),(TRUE, 12, 6),(FALSE, 12, 5), 
(FALSE, 12, 6),(FALSE, 12, 6),(TRUE, 12, 4), 
-- Avilés Hurtado
(TRUE, 13, 4),(TRUE, 13, 6),(TRUE, 13, 3), 
(TRUE, 13, 5),(TRUE, 13, 4),(TRUE, 13, 2), 
(FALSE, 13, 11),  
-- Borja Bastón
(FALSE, 14, 6),(TRUE, 14, 6),(TRUE, 14, 5), 
(TRUE, 14, 1),(FALSE, 14, 9),(TRUE, 14, 4), 
(TRUE, 14, 5),(TRUE, 14, 1),(TRUE, 14, 6),  
(TRUE, 14, 2),(FALSE, 14, 6),(TRUE, 14, 6),  
(TRUE, 14, 6),(FALSE, 14, 6),(TRUE, 14, 6),  
(FALSE, 14, 8),(TRUE, 14, 3),(TRUE, 14, 1),  
(TRUE, 14, 6),(TRUE, 14, 5),(TRUE, 14, 5),  
(TRUE, 14, 6),(TRUE, 14, 2),(FALSE, 14, 4), 
(FALSE, 14, 14),  
-- Pablo Barrera
(FALSE, 15, 5),(TRUE, 15, 3),(TRUE, 15, 3),  
(TRUE, 15, 6),(TRUE, 15, 6),(TRUE, 15, 2),  
(FALSE, 15, 4),(TRUE, 15, 5),(TRUE, 15, 4),   
(TRUE, 15, 2),  
-- Harold Preciado
(TRUE, 16, 6),(TRUE, 16, 5),(FALSE, 16, 14),   
(TRUE, 16, 4),(TRUE, 16, 1);   	    	            


INSERT INTO partidos (idEquipo, idEquipoContrario, fecha, torneo, sede, arranque, marcadorF, marcadorC, minuto, ronda) VALUES
-- partidos tigres
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2024-08-24', 'LigaMXAP24', 'Local', TRUE, 0, 0, 42, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2024-07-06', 'LigaMXAP24', 'Local', TRUE, 0, 0, 19, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = ' Colombus'), '2024-04-09', 'ConcacafChampionsCup', 'Local',1, 0, 0, 90, 'Cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2023-12-03', 'LigaMXAP23', 'Local', TRUE, 0, 0, 9, 'Cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), '2023-10-07', 'LigaMXAP23', 'visitante', TRUE, 0, 0, 8, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2023-09-23', 'LigaMXAP23', 'Local', TRUE, 1, 0, 59, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2023-09-02', 'LigaMXAP23', 'Local', TRUE, 2, 0, 49, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2023-05-28', 'LigaMXCL23', 'visitante', TRUE, 0, 2, 65, 'Final'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Toluca'), '2023-05-11', 'LigaMXCL23', 'Local', TRUE, 1, 1, 31, 'Cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2023-04-20', 'LigaMXCL23', 'local', TRUE, 0, 0, 49, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2023-03-11', 'LigaMXCL23', 'local', TRUE, 2, 1, 44, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), '2022-10-13', 'LigaMXAP22', 'local', TRUE, 0, 0, 88, 'Cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2022-05-21', 'LigaMXCL22', 'Local', TRUE, 2, 1, 74, 'Semifinal'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2022-05-21 ', 'LigaMXCL22', 'Local', TRUE, 0, 1, 54, 'Semifinal'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Mazatlan'), '2022-02-06', 'LigaMXCL22', 'Local', TRUE, 2, 2, 76, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2022-01-23', 'LigaMXCL22', 'visitante', TRUE, 1, 1, 97, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2022-01-15', 'LigaMXCL22', 'Local', TRUE, 0, 2, 88, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2021-04-24', 'LigaMXCL21', 'Local', TRUE, 1, 1, 64, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Mazatlan'), '2021-03-13', 'LigaMXCL21', 'Local', TRUE, 0, 2, 70, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2021-03-05', 'LigaMXCL21', 'visitante', TRUE, 1, 1, 11, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'San'), '2020-10-03', 'LigaMXAP20', 'Local', TRUE, 1, 0, 70, 'lar Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Toluca'), '2020-08-16', 'LigaMXAP20', 'visitante', TRUE, 1, 2, 72, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2020-08-11', 'LigaMXAP20', 'Local', TRUE, 0, 0, 6, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2020-02-29', 'LigaMXCL20', 'Local', TRUE, 1, 0, 56, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2020-02-29 ', 'LigaMXCL20', 'Local', TRUE, 0, 0, 50, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2020-02-08', 'LigaMXCL20', 'Local', TRUE, 1, 0, 62, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'America'), '2019-11-28', 'LigaMXAP19', 'visitante', TRUE, 1, 1, 67, 'Cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2019-10-05', 'LigaMXAP19', 'Local', TRUE, 2, 0, 48, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2019-08-27', 'LigaMXAP19', 'visitante', TRUE, 0, 0, 29, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2019-02-22', 'LigaMXCL19', 'visitante', TRUE, 0, 0, 93, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2019-01-05', 'LigaMXCL19', 'visitante', TRUE, 1, 2, 95, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'TIGRES'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2018-08-19', 'LigaMxAP18', 'visitante', TRUE, 0, 0, 9, 'Regular Season'),
-- partidos monterrey
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), '2024-09-18', 'LigaMXAP24', 'Local', TRUE, 1, 2, 79, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2024-07-20', 'LigaMXAP24', 'Local', TRUE, 0, 0, 28, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2023-09-16', 'LigaMXAP23', 'local',1, 1, 0, 46, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2023-09-03', 'LigaMXAP23', 'visitante', TRUE, 1, 0, 36, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Valladolid'), '2023-02-18', 'LaLiga', 'Local', TRUE, 1, 1, 49, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Getafe'), '2021-02-19', 'LaLiga', 'Local', TRUE, 0, 0, 76, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sevilla'), '2021-01-02', 'LaLiga', 'Local', TRUE, 0, 1, 53, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Levante'), '2020-12-29', 'LaLiga', 'visitante', TRUE, 1, 4, 78, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Athletic Club'), '2020-06-20', 'LaLiga', 'visitante', TRUE, 0, 1, 86, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Granada'), '2020-06-15', 'LaLiga', 'Local', TRUE, 0, 1, 85, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Mallorca'), '2020-02-21', 'LaLiga', 'Local', TRUE, 0, 1, 19, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Barcelona'), '2020-02-09', 'LaLiga', 'Local', TRUE, 0, 0, 6, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atletico de Madrid'), '2019-02-03', 'LaLiga', 'Local', TRUE, 0, 0, 65, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), (SELECT idEquipo FROM equipos WHERE nombre = 'Girona'), '2019-01-20', 'LaLiga', 'Local', TRUE, 2, 2, 94, 'Regular Season'),
-- partidos del america
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'CruzAzul'), '2024-05-26', 'LigaMXCL24', 'local', TRUE, 0, 0, 78, 'Final'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2024-04-20', 'LigaMXCL24', 'visitante', TRUE, 0, 0, 20, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2024-03-02', 'LigaMXCL24', 'visitante',1, 1, 1, 56, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tigres'), '2023-12-14', 'LigaMXAP23', 'visitante', TRUE, 0, 0, 51, 'Final'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2023-04-22', 'LigaMXCL23', 'local', TRUE, 0, 1, 72, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2023-02-11', 'LigaMXCL23', 'local', TRUE, 1, 0, 51, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2023-02-04', 'LigaMXCL23', 'visitante', TRUE, 0, 2, 53, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Toluca'), '2023-01-14', 'LigaMXCL23', 'visitante', TRUE, 1, 2, 76, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2022-09-17', 'LigaMXAP22', 'local', TRUE, 0, 0, 4, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'America'), (SELECT idEquipo FROM equipos WHERE nombre = 'SanLuis'), '2022-09-06', 'LigaMXAP22', 'local', TRUE, 3, 0, 89, 'Regular Season'),
-- partidos de san luis
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2024-08-18', 'LigaMXAP24', 'local', TRUE, 3, 0, 86, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'America'), '2024-03-29', 'LigaMXCL24', 'visitante', TRUE, 0, 2, 95, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sarpsborg'), '2019-07-15', 'Eliteserien', 'local', TRUE, 1, 2, 48, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Kristiansund'), '2019-06-23', 'Eliteserien', 'visitante', TRUE, 0, 0, 89, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Bodo'), '2019-04-28', 'Eliteserien', 'local', TRUE, 1, 0, 25, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Stromsgodset'), '2018-11-24', 'Eliteserien', 'local', TRUE, 0, 0, 17, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Brann'), '2018-10-21', 'Eliteserien', 'local', TRUE, 0, 0, 5, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Lillestrom'), '2018-09-30', 'Eliteserien', 'visitante', TRUE, 0, 1, 69, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Ranheim'), '2018-09-23', 'Eliteserien', 'local', TRUE, 0, 1, 38, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sandefjord'), '2018-09-01', 'Eliteserien', 'local', TRUE, 2, 3, 89, 'Regular Season'),
-- partidos del cruz azul
((SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2024-08-23', 'LigaMXAP24', 'visitante', TRUE, 0, 0, 45, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2024-07-13', 'LigaMXAP24', 'visitante', TRUE, 1, 0, 28, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), (SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), '2024-02-10', 'LigaMXCL24', 'local', TRUE, 0, 0, 38, 'Regular Season'),
-- partido de pumas
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2024-08-24', 'LigaMXAP24', 'visitante',1, 0, 0, 9, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), '2024-07-21', 'LigaMXAP24', 'Local', TRUE, 1, 0, 51, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tigres'), '2023-12-10', 'LigaMXAP23', 'visitante', TRUE, 0, 0, 16, 'semifinal'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2023-12-03', 'LigaMXAP23', 'Local', TRUE, 1, 0, 18, 'cuartos'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), '2023-10-07', 'LigaMXAP23', 'visitante', TRUE, 0, 0, 30, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2023-09-22', 'LigaMXAP23', 'visitante', TRUE, 1, 0, 67, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'puma'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2023-09-22', 'LigaMXAP23', 'visitante', TRUE, 0, 0, 8, 'Regular Season'),
-- partidos de tijuana
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2024-08-23', 'LigaMXAP24', 'local', TRUE, 0, 1, 35, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), '2024-07-12', 'LigaMXAP24', 'local', FALSE, 2, 1, 86, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2024-03-15', 'LigaMXCL24', 'local', TRUE, 1, 1, 70, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2024-03-10', 'LigaMXCL24', 'visitante', TRUE, 2, 3, 76, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2024-03-10', 'LigaMXCL24', 'visitante', TRUE, 1, 3, 53, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2024-03-10', 'LigaMXCL24', 'visitante', TRUE, 0, 2, 29, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2024-03-03', 'LigaMXCL24', 'local', TRUE, 0, 1, 99, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), '2024-02-03', 'LigaMXCL24', 'visitante', TRUE, 0, 2, 33, 'Regular Season'),
-- partidos de atlas
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2024-02-04', 'LigaMXCL24', 'Local', TRUE, 1, 0, 46, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tigres'), '2022-05-21', 'LigaMXCL22', 'visitante', TRUE, 1, 4, 99, 'semifinal'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2021-12-12', 'LigaMXAP21', 'local', FALSE, 1, 1, 90, 'final'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Chivas'), '2021-10-02', 'LigaMXAP21', 'Visitante', TRUE, 0, 0, 27, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2021-09-28', 'LigaMXAP21', 'local', FALSE, 0, 1, 54, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2021-04-30', 'LigaMXCL21', 'Visitante', TRUE, 3, 1, 88, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), '2020-10-16', 'LigaMXAP20', 'Local', TRUE, 1, 0, 9, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2020-03-13', 'LigaMXCL20', 'local', TRUE, 1, 0, 52, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2020-03-13', 'LigaMXCL20', 'local', TRUE, 0, 0, 44, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), '2020-02-28', 'LigaMXCL20', 'local', TRUE, 1, 3, 84, 'Regular Season'),
-- partidos de guadalajara
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2024-09-18', 'LigaMXAP24', 'Local', TRUE, 0, 0, 50, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), '2024-08-31', 'LigaMXAP24', 'Local', TRUE, 2, 0, 44, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2024-03-09', 'LigaMXCL24', 'Local', TRUE, 0, 2, 95, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2023-10-31', 'LigaMXAP23', 'Visitante', TRUE, 1, 0, 34, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2023-10-20', 'LigaMXAP23', 'Visitante', TRUE, 0, 0, 25, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2023-10-07', 'LigaMXAP23', 'Local', TRUE, 3, 1, 93, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Guadalajara'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2023-08-26', 'LigaMXAP23', 'Visitante', TRUE, 0, 2, 84, 'Regular Season'),
-- partidos de necaxa
((SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), '2024-10-18', 'LigaMXCL24', 'Local', TRUE, 0, 1, 34, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2024-09-01', 'LigaMXAP24', 'Visitante', TRUE, 0, 0, 34, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), (SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), '2024-08-24', 'LigaMXAP24', 'Local', TRUE, 0, 0, 31, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2024-05-02', 'LigaMXAP24', 'Visitante', TRUE, 2, 3, 99, 'final'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tijuana'), '2024-04-05', 'LigaMXAP24', 'Visitante', TRUE, 1, 2, 85, 'Regular Season'),
-- partidos leon
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2024-07-21', 'LigaMXAP24', 'Local', TRUE, 0, 1, 63, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Portimonense'), '2024-04-21', 'LigaPortugal', 'Local', TRUE, 0, 1, 55, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Gil Vicente'), '2024-03-29', 'LigaPortugal', 'Visitante', TRUE, 0, 0, 49, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Braga'), '2024-01-18', 'LigaPortugal', 'Local', TRUE, 0, 0, 62, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Boavista'), '2023-09-30', 'LigaPortugal', 'Visitante', TRUE, 0, 0, 12, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Benfica'), '2019-04-14', 'LigaPortugal', 'Visitante', TRUE, 1, 4, 88, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), (SELECT idEquipo FROM equipos WHERE nombre = 'Vitoria'), '2019-02-23', 'LigaPortugal', 'Local', TRUE, 0, 1, 80, 'Regular Season'),
-- partidos Puebla
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2024-07-16', 'LigaMXAP24', 'Local', TRUE, 1, 2, 91, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), '2024-07-05', 'LigaMXAP24', 'Local', TRUE, 0, 0, 96, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2024-01-19', 'LigaMXCL24', 'Local', TRUE, 0, 0, 59, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Vancouver'), '2022-05-28', 'MLS', 'Visitante', TRUE, 0, 0, 24, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Dallas'), '2022-05-18', 'MLS', 'Local', TRUE, 1, 1, 92, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'LA Galaxy'), '2020-03-07', 'MLS', 'visitante', TRUE, 1, 0, 89, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), '2019-08-24', 'LigaMXAP19', 'visitante', TRUE, 1, 1, 88, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Veracruz'), '2019-01-25', 'LigaMXCL19', 'visitante', TRUE, 0, 0, 20, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), '2019-01-04', 'LigaMXCL19', 'Local', TRUE, 0, 1, 29, 'Regular Season'),
-- partido de juarez
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2024-07-05', 'LigaMXAP24', 'Local', FALSE, 1, 1, 72, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2023-10-07', 'LigaMXAP23', 'Visitante', TRUE, 0, 3, 52, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2023-09-22', 'LigaMXAP23', 'Local', TRUE, 0, 2, 69, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2023-08-22', 'LigaMXAP23', 'Local', FALSE, 3, 1, 81, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Chivas'), '2023-08-18', 'LigaMXAP23', 'Local', FALSE, 0, 1, 84, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2022-10-23', 'LigaMXAP22', 'Visitante', FALSE, 0, 0, 95, 'semifinal'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), (SELECT idEquipo FROM equipos WHERE nombre = 'Tigres'), '2017-12-10', 'LigaMXAP17', 'Local', TRUE, 1, 2, 82, 'final'),
-- Partido de pachuca
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), '2024-08-31', 'LigaMXAP24', 'Local', TRUE, 0, 1, 55, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Burgos'), '2024-02-17', 'LaLiga2', 'Local', FALSE, 4, 0, 89, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Eldense'), '2024-02-04', 'LaLiga2', 'Local', TRUE, 0, 1, 71, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sporting'), '2022-12-17', 'LaLiga2', 'Local', TRUE, 0, 0, 74, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Ponferradina'), '2022-11-19', 'LaLiga2', 'Visitante', TRUE, 1, 1, 98, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Malaga'), '2022-10-24', 'LaLiga2', 'Local', TRUE, 0, 0, 50, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Racing de Santander'), '2022-08-28', 'LaLiga2', 'Visitante', TRUE, 0, 0, 53, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leganes'), '2022-08-21', 'LaLiga2', 'Local', TRUE, 0, 0, 80, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'UD Ibiza'), '2022-05-29', 'LaLiga2', 'Local', TRUE, 2, 2, 95, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Zaragoza'), '2022-05-16', 'LaLiga2', 'Local', TRUE, 0, 0, 14, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Zaragoza'), '2022-05-16', 'LaLiga2', 'local', TRUE, 3, 3, 71, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Mirandes'), '2022-04-30', 'LaLiga2', 'Local', TRUE, 1, 0, 57, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Lugo'), '2022-03-19', 'LaLiga2', 'Visitante', TRUE, 0, 1, 92, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Sociedad B'), '2022-02-26', 'LaLiga2', 'Local', TRUE, 0, 1, 91, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Burgos'), '2022-02-20', 'LaLiga2', 'Visitante', TRUE, 0, 0, 60, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Valladolid'), '2021-12-12', 'LaLiga2', 'Visitante', TRUE, 1, 2, 59, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Las Palmas'), '2021-11-06', 'LaLiga2', 'Local', TRUE, 0, 0, 21, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Burgos'), '2021-10-21', 'LaLiga2', 'Local', TRUE, 0, 1, 57, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cartagena'), '2021-09-12', 'LaLiga2', 'Local', TRUE, 0, 0, 48, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sporting'), '2020-12-21', 'LaLiga2', 'Visitante', TRUE, 0, 1, 96, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Logroñes'), '2020-10-17', 'LaLiga2', 'Visitante', TRUE, 0, 0, 31, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Birmingham'), '2019-08-25', 'Championship', 'Local', TRUE, 2, 0, 75, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Birmingham'), '2019-08-21', 'Championship', 'Visitante', TRUE, 1, 1, 70, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Real Sociedad'), '2017-12-10', 'LaLiga', 'Visitante', TRUE, 1, 0, 58, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Pachuca'), (SELECT idEquipo FROM equipos WHERE nombre = 'Sporting'), '2014-02-16', 'LaLiga2', 'Local', TRUE, 0, 1, 30, 'Regular Season'),
--  partido de queretaro
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2024-05-02', 'LigaMXCL24', 'Visitante', FALSE, 1, 0, 75, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2024-04-06', 'LigaMXCL24', 'Visitante', TRUE, 1, 0, 75, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2024-03-31', 'LigaMXCL24', 'Visitante', TRUE, 1, 2, 70, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'San Luis'), '2024-02-27', 'LigaMXCL24', 'Local', TRUE, 2, 0, 48, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Chivas'), '2023-10-31', 'LigaMXAP23', 'Local', TRUE, 0, 2, 55, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Juarez'), '2023-03-19', 'LigaMXCL23', 'Local', TRUE, 1, 2, 87, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Atlas'), '2023-01-22', 'LigaMXCL23', 'local', TRUE, 0, 0, 21, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Toluca'), '2020-02-15', 'LigaMXCL20', 'Visitante', TRUE, 0, 1, 34, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Necaxa'), '2019-07-28', 'LigaMXAP19', 'Local', FALSE, 1, 0, 71, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Queretaro'), (SELECT idEquipo FROM equipos WHERE nombre = 'Cruz Azul'), '2019-04-20', 'LigaMXCL19', 'Visitante', TRUE, 0, 2, 64, 'Regular Season'),
-- partido de santos
((SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), (SELECT idEquipo FROM equipos WHERE nombre = 'Puebla'), '2024-01-30', 'LigaMXCL24', 'Local', TRUE, 0, 0, 65, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), (SELECT idEquipo FROM equipos WHERE nombre = 'Leon'), '2024-01-27', 'LigaMXCL24', 'Visitante', TRUE, 0, 0, 43, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), (SELECT idEquipo FROM equipos WHERE nombre = 'Chivas'), '2024-01-13', 'LigaMXCL24', 'Visitante', FALSE, 1, 1, 94, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), (SELECT idEquipo FROM equipos WHERE nombre = 'Monterrey'), '2023-04-16', 'LigaMXCL23', 'Visitante', TRUE, 1, 1, 94, 'Regular Season'),
((SELECT idEquipo FROM equipos WHERE nombre = 'Santos'), (SELECT idEquipo FROM equipos WHERE nombre = 'Pumas'), '2023-01-14', 'LigaMXCL23', 'Local', TRUE, 2, 0, 87, 'Regular Season');
